### PR TITLE
Preserve stacktraces for async/await

### LINKED ISSUE #536: Exceptions throw in `test('.', async (t) => { ... })` do not have meaningful stacktrace
When using `tape@5` instead of `tape@4` a programmer error in my test program is captured by `tape` and showing a `not ok ${err.message}`

```
# sync
not ok 1 TypeError: Cannot read property 'length' of undefined
  ---
    operator: fail
    stack: |-
      Error: TypeError: Cannot read property 'length' of undefined
          at Test.assert [as _assert] (/tape/lib/test.js:260:54)
          at Test.bound [as _assert] (tape/lib/test.js:84:32)
          at Test.fail (tape/lib/test.js:354:10)
          at Test.bound [as fail] (tape/lib/test.js:84:32)
          at onError (tape/lib/test.js:114:18)
  ...
```

The stack trace is the stack trace of tape itself handling `promise.catch()` ( https://github.com/substack/tape/blob/master/lib/test.js#L113 ) instead of the stack trace for my code.

I cannot tell which line of code in my test function has `.length of undefined` because tape is printing the wrong stack trace.

Ideally tape would rethrow the `err` to the global process uncaught exception handler so that I can see the real stack trace and so that the tests can fail hard and fast immediately.

### PR DESCRIPTION
**Pull request by Raynos**
We use `self.ifError(err)` instead of `self.fail()`
which logs the original stacktrace instead of creating
a new Error object.

Fixes #536

### CODE REVIEW

File: lib/test.js [hunk 1]
```diff
@@ -111,7 +112,11 @@ Test.prototype.run = function () {
                 self.end();
             }
         })['catch'](function onError(err) {
-            self.fail(err);
+            if (objectToString(err) === '[object Error]') {
```
Comment (ljharb) [inline lib/test.js:115]: I think this will only work for Error, not for the 6 builtin subclasses nor for user subclasses.

Comment (Raynos) [reply lib/test.js:115]: do you have a preferred `is-error` library ?

I can also do `err instanceof Error || objectToString(err) === '[object Error]'`

`instanceof` should work for everything except cross realm which rarely happens ...

**Comment by Raynos** [comment]
Addressed feedback.

File: lib/test.js (hunk 1 above)
Comment (ljharb) [reply lib/test.js]: Given that there's no robust way to identify Errors, cross-realm or otherwise, this seems like it'd be good enough.

File: test/async-await.js [hunk 2]
```diff
@@ -245,3 +246,49 @@ tap.test('async-error', function (t) {
         t.end();
     });
 });
+
+tap.test('async-bug', function (t) {
+    runProgram('async-await', 'async-bug.js', function (r) {
+        var stdout = r.stdout.toString('utf8');
+        var lines = stdout.split('\n');
+        lines = lines.filter(function (line) {
+            return ! /^(\s+)at(\s+)<anonymous>$/.test(line);
```
Comment (ljharb) [inline test/async-await.js:255]: can you elaborate on why these lines need filtering out?

Comment (Raynos) [reply test/async-await.js]: I guess they don't that's just copy paste from a different test block, i glossed over it.

Comment (Raynos) [reply test/async-await.js]: Ok, removed the copy/paste stuff.

**Comment by Raynos** [comment]
Cleaned up the test, this looks good to merge to me.

**Comment by ljharb** [comment]
I’m going to land #538 first and rebase this, so i can be sure tests pass in all relevant node versions, and then I’ll land this one.

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
I'll fix these last failing tests, and land this tonight.
