### PR TITLE
fix stack where actual==falsy

### LINKED ISSUE #399: failure doesn't produce stacks if actual value is falsy
https://github.com/substack/tape/blob/b66f8f80928bb82f0817407880a139ad118daf01/lib/results.js#L160

    test('failureStacks', function(t) {
      t.equal(true, false); // returns a full stack
      t.equal(false, true); // no stack
      t.end();
    });

### PR DESCRIPTION
**Pull request by nhamer**
Fixes #399

### CODE REVIEW

File: lib/results.js [hunk 1]
```diff
@@ -157,7 +157,7 @@ function encodeResult (res, count) {
         output += inner + 'at: ' + res.at + '\n';
     }
 
-    var actualStack = res.actual && res.actual.stack;
+    var actualStack = res.actual !== undefined && res.actual.stack;
```
Comment (ljharb) [inline lib/results.js]: this will cause it to throw if `res.actual` is `null`.

If `res.actual` is a primitive (even a truthy primitive), `.stack` will never have a meaningful value.

This check should probably really be `res.actual && (typeof res.actual === 'object' || typeof res.actual === 'function') ? res.actual.stack : null`

Comment (nhamer) [reply lib/results.js]: I'm working slightly retarded here, on windows a lot of the unit tests fail. Will update the pr.

Comment (nhamer) [reply lib/results.js]: Oh, I see. It was working on my machine for the wrong reason. The actual bug is:

when res.actual === false,
res.actual && res.actual.stack === false, not undefined

Comment (ljharb) [reply lib/results.js]: @nhamer fyi, i edited your comment to remove the inappropriate word.

**Comment by nhamer** [comment]
it was the inverse of the existing test; fixed the existing test's assertion to accurately reflect its arguments
